Add prettier
ianobermiller/redux-react-hook pull request #7
Opened 2018-10-30 09:05 UTC by andrewesterhuizen

Hey Ian! I've added prettier with some basic rules and a npm script to run it on the source and example code. I have also added it to run with the npm prepare script but I wasn't completely sure if this is the right stage to run it. Please let me know if you think there's anything I should change or add or if there are any other issues.

2018-10-31 04:03 UTC, ianobermiller requested changes
Thanks for picking up this task! Sorry for the churn! Just fix the config and rebase and you should be good to go!

2018-10-31 04:03 UTC, ianobermiller commented on .prettierrc
> +}
```
{
  "bracketSpacing": false,
  "jsxBracketSameLine": true,
  "printWidth": 80,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false
}
```

2018-10-31 04:03 UTC, ianobermiller commented on .prettierrc
> +}
Let's also add the rest of the config options. In particular I don't want `bracketSpacing` :)

2018-10-31 04:03 UTC, ianobermiller commented on package.json
> +    "prepare": "yarn run prettier && yarn run build",
lgtm

2018-11-01 18:08 UTC, andrewesterhuizen commented
@ianobermiller Sorry for the delay in working on this, I've updated the config now and fixed the merge conflicts. Please let me know if theres anything else you think needs to change.

2018-11-02 03:16 UTC, ianobermiller commented
No worries, it's open source, no rush! Thanks for taking this on and fixing it up!

2018-11-02 03:16 UTC, merged